jobs:
  build:
    env:
      MAVEN_ARGS: -e -B -DtrimStackTrace=false
    permissions:
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Maven version
      run: 'mvn --version

        mkdir -p target

        '
    - continue-on-error: true
      name: Initialize CodeQL
      uses: github/codeql-action/init@8aff97f12c99086bdb92ff62ae06dbbcdf07941b
      with:
        languages: java
    - continue-on-error: true
      name: Maven build
      run: 'mvn install site

        '
    - continue-on-error: true
      name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@8aff97f12c99086bdb92ff62ae06dbbcdf07941b
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN_GH }}
      if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/website')
        || startsWith(github.ref, 'refs/tags/v'))
      name: Website
      run: 'chmod +x ./.github/website.sh

        .github/website.sh

        '
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
permissions:
  contents: read
