jobs:
  Fuzzing:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: build
      name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@01544e953848869e7e359156d2b1a877deb98286
      with:
        dry-run: false
        language: jvm
        oss-fuzz-project-name: joda-time
    - continue-on-error: true
      name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@01544e953848869e7e359156d2b1a877deb98286
      with:
        dry-run: false
        fuzz-seconds: 300
        language: jvm
        oss-fuzz-project-name: joda-time
    - continue-on-error: true
      if: failure() && steps.build.outcome == 'success'
      name: Upload Crash
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./out/artifacts
name: CIFuzz
on:
  repository_dispatch:
    types: trigger-ga___cifuzz.yml
permissions:
  actions: read
  contents: read
