jobs:
  tzdbcheck:
    env:
      MAVEN_ARGS: -e -B -DtrimStackTrace=false
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        token: ${{ secrets.PERSONAL_TOKEN_GH }}
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
      with:
        cache: maven
        distribution: corretto
        java-version: '8'
    - continue-on-error: true
      name: Maven version
      run: 'mvn --version

        mkdir -p target

        '
    - continue-on-error: true
      name: Get current version
      run: 'CURRENT_TZDB=$(mvn help:evaluate -Dexpression=tz.database.version -q -DforceStdout)

        echo "current: $CURRENT_TZDB"

        echo "CURRENT_TZDB=$CURRENT_TZDB" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Get latest version
      run: 'git clone https://github.com/JodaOrg/global-tz.git tz

        cd tz

        git checkout global-tz

        LATEST_TZDB=$(git describe --abbrev=0 --tags)

        echo "latest: $LATEST_TZDB"

        echo "LATEST_TZDB=$LATEST_TZDB" >> $GITHUB_ENV

        '
      working-directory: target
    - continue-on-error: true
      name: Compare versions
      run: 'echo "current: $CURRENT_TZDB"

        echo "latest:  $LATEST_TZDB"

        if [ "$CURRENT_TZDB" == "$LATEST_TZDB" ]; then echo "NOOP=true" >> $GITHUB_ENV;
        fi

        '
    - continue-on-error: true
      if: env.NOOP != 'true'
      name: Checkout tzdb release
      run: 'git checkout global-tz

        git reset --hard ${LATEST_TZDB} --

        git status

        '
      working-directory: target/tz
    - continue-on-error: true
      if: env.NOOP != 'true'
      name: Copy files
      run: 'ls -l target/tz

        \cp target/tz/africa src/main/java/org/joda/time/tz/src

        \cp target/tz/antarctica src/main/java/org/joda/time/tz/src

        \cp target/tz/asia src/main/java/org/joda/time/tz/src

        \cp target/tz/australasia src/main/java/org/joda/time/tz/src

        \cp target/tz/backward src/main/java/org/joda/time/tz/src

        \cp target/tz/etcetera src/main/java/org/joda/time/tz/src

        \cp target/tz/europe src/main/java/org/joda/time/tz/src

        \cp target/tz/northamerica src/main/java/org/joda/time/tz/src

        \cp target/tz/southamerica src/main/java/org/joda/time/tz/src

        ls -l src/main/java/org/joda/time/tz/src

        '
    - continue-on-error: true
      if: env.NOOP != 'true'
      name: Update build with new tzdb
      run: 'sed -i ''s/$CURRENT_TZDB/${LATEST_TZDB}/g'' src/main/java/org/joda/time/tz/src/Readme.txt

        mvn versions:set-property -DnewVersion=${LATEST_TZDB} -Dproperty=tz.database.version
        -DgenerateBackupPoms=false

        mvn install

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN_GH }}
      id: createpr
      if: env.NOOP != 'true'
      name: Create Pull Request
      uses: peter-evans/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
      with:
        assignees: jodastephen
        author: Stephen Colebourne (CI) <scolebourne@joda.org>
        base: main
        body: Update time zone data to ${{ env.LATEST_TZDB }}
        branch: bot/update-tzdb
        commit-message: Update time zone data to ${{ env.LATEST_TZDB }}
        committer: Stephen Colebourne (CI) <scolebourne@joda.org>
        labels: TZDB
        title: Update time zone data to ${{ env.LATEST_TZDB }}
        token: ${{ secrets.GITHUB_TOKEN }}
name: TZDB check
on:
  repository_dispatch:
    types: trigger-ga___tzdbupdate.yml
permissions:
  contents: read
